version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: chyi

networks:
  fnet:
    driver: bridge
